language: rust

cache: cargo

rust:
  - stable

before_script:
  - sudo apt update
  - sudo apt install cmake
  - rustup component add clippy

script:
  - cargo fmt --check
  - cargo clippy
  - cargo test